//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionesEmpresas
    {
        public int IdEncuesta { get; set; }
        public int cod_empresa { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Encuestas Encuestas { get; set; }
    }
}
