//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcionesSeleccionMultiple
    {
        public int IdSeleccionMultiple { get; set; }
        public string Valor { get; set; }
        public long Id { get; set; }
    
        public virtual SeleccionMultiples SeleccionMultiples { get; set; }
    }
}
