//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class climaEntities : DbContext
    {
        public climaEntities()
            : base("name=climaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afirmaciones> Afirmaciones { get; set; }
        public virtual DbSet<AsignacionesEmpresas> AsignacionesEmpresas { get; set; }
        public virtual DbSet<Dimensiones> Dimensiones { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<EncuestaPreguntas> EncuestaPreguntas { get; set; }
        public virtual DbSet<Encuestas> Encuestas { get; set; }
        public virtual DbSet<EvaluacionAfirmaciones> EvaluacionAfirmaciones { get; set; }
        public virtual DbSet<OpcionesSeleccionMultiple> OpcionesSeleccionMultiple { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<SeleccionMultiples> SeleccionMultiples { get; set; }
        public virtual DbSet<TipoPreguntas> TipoPreguntas { get; set; }
    }
}
