//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaPreguntas
    {
        public int IdEncuesta { get; set; }
        public short IdTipoPregunta { get; set; }
        public Nullable<int> IdAfirmacion { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public long Id { get; set; }
        public Nullable<int> IdSeleccionMultiple { get; set; }
    
        public virtual Afirmaciones Afirmaciones { get; set; }
        public virtual Encuestas Encuestas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
        public virtual SeleccionMultiples SeleccionMultiples { get; set; }
        public virtual TipoPreguntas TipoPreguntas { get; set; }
    }
}
