//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        public long IdRespuesta { get; set; }
        public short IdTipoPregunta { get; set; }
        public int IdEncuesta { get; set; }
        public string login { get; set; }
        public int IdConsulta { get; set; }
        public string Respuesta { get; set; }
    
        public virtual Encuestas Encuestas { get; set; }
        public virtual TipoPreguntas TipoPreguntas { get; set; }
    }
}
